title: Misturas
backgrounds:
  - static/assets/background/background_0.jpeg
  - static/assets/background/background_1.jpeg
background-interval-ms: 7000
background-overlay: 0.52
github-link:
  text: Github
  href: https://github.com/milena-paz

